# Generated by Django 5.1.4 on 2025-01-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='grade',
            field=models.CharField(choices=[('rookie', 'Новичок'), ('pro', 'Профессионал'), ('master', 'Мастер')], max_length=15),
        ),
    ]
