# Generated by Django 5.1.4 on 2025-01-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard_app', '0002_driver_slug_user_slug_alter_driver_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
