# Generated by Django 5.1.4 on 2025-01-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard_app', '0003_remove_user_login_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
