# Generated by Django 5.1.4 on 2025-01-18 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('risk_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('bank_details', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passport_details', models.CharField(max_length=255)),
                ('contact_details', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesystem.insuranceagent')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('insurance_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesystem.insuranceagent')),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('collective', 'Collective'), ('individual', 'Individual')], default='collective', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_payout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employees', models.ManyToManyField(to='insurancesystem.employee')),
                ('insurance_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesystem.insuranceagent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesystem.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('decision', models.BooleanField()),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancesystem.collectivecontract')),
            ],
        ),
    ]
