# Generated by Django 5.1.4 on 2025-01-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceagent',
            name='user',
        ),
    ]
