# Generated by Django 5.1.4 on 2025-01-21 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancesystem', '0002_remove_insuranceagent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecase',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurancesystem.employee'),
        ),
    ]
